# Generated by Django 4.0.1 on 2022-01-20 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom_user',
            name='security_question',
            field=models.CharField(choices=[('FV', 'Favorite Team'), ('HN', 'Highschool Nick Name')], max_length=2),
        ),
    ]
