# Generated by Django 4.0.1 on 2022-02-05 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_todolistitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolistitem',
            name='done',
            field=models.CharField(default='Y', max_length=1),
            preserve_default=False,
        ),
    ]
