# Generated by Django 4.0.1 on 2022-02-05 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_todolistitem_date_diff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolistitem',
            name='date_diff',
            field=models.IntegerField(),
        ),
    ]
