# Generated by Django 4.0.1 on 2022-02-05 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_todolistitem_date_diff'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolistitem',
            name='date_diff',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
